/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.StudentController;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.StudentDAO;


/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    btnlogin.addActionListener(e -> performLogin());
    setLogo();

    }

    private void performLogin() {
    String userId = txtID.getText().trim();
    String passwordText = new String(password.getPassword());

    if (userId.isEmpty() || passwordText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter both User ID and Password");
        return;
    }

    try (java.sql.Connection conn = model.DatabaseManager.getConnection()) {
        
        String adminSql = "SELECT * FROM admin WHERE admin_id = ? AND password = ?";
        java.sql.PreparedStatement pstAdmin = conn.prepareStatement(adminSql);
        pstAdmin.setString(1, userId);
        pstAdmin.setString(2, passwordText);
        java.sql.ResultSet rsAdmin = pstAdmin.executeQuery();

        if (rsAdmin.next()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "Admin login successful!");
            openMainFrame(true, userId);
            this.dispose();
            return;
        }

        String studentSql = "SELECT * FROM students WHERE id = ?";
        java.sql.PreparedStatement pstStudent = conn.prepareStatement(studentSql);
        pstStudent.setString(1, userId);
        java.sql.ResultSet rsStudent = pstStudent.executeQuery();

        if (rsStudent.next()) {
            
            if (passwordText.equals("student123")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Student login successful!");
                openMainFrame(false, userId);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Incorrect password for student.");
            }
            return;
        }

       
        javax.swing.JOptionPane.showMessageDialog(this, "User ID not found.");

    } catch (Exception ex) {
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Login error: " + ex.getMessage());
    }
}
private void setLogo() {
       
       ImageIcon icon = new ImageIcon(getClass().getResource("/View/geometric-1732847_1280.jpg"));
        jLabel3.setIcon(icon);

    }
private void openMainFrame(boolean isAdmin, String userId) {
    
    Stdmanagement mainFrame = new Stdmanagement(isAdmin, userId);
    new StudentController(new StudentDAO(), mainFrame); 
    mainFrame.setVisible(true);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 246, 39));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 246, 39));

        btnlogin.setBackground(new java.awt.Color(255, 51, 51));
        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnlogin.setText("Log In");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 400, 47));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 108, 39));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 108, 39));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Students Acadamic Management System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 430, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setText("ABC University");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/geometric-1732847_1280.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
         UIManager.setLookAndFeel(new FlatLightLaf());
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
